[functions]
  # Указываем, где лежат наши функции
  directory = "netlify/functions/"

# Добавляем блок для задач по расписанию
# DISABLED: Cron job отключен для экономии лимитов
# [functions."process-renewals"]
#   # Cron-выражение: "в 3 часа ночи по UTC каждый день"
#   # Можете поменять на "0 * * * *" для теста (каждый час)
#   schedule = "0 3 * * *"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Cache static assets aggressively on the CDN
[[headers]]
  for = "/*.(png|jpg|jpeg|gif|webp|avif|svg)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.(css|js)"
  [headers.values]
    Cache-Control = "public, max-age=604800"
